Change != comparison to `is not` in ordered_arguments.
Using != causes issues for parameters that have np.array default values, since np.arrays override comparison to be elementwise. This then causes an error:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Using `is not` instead will work here since `param.empty` is actually a module-level sentinel value (`inspect._empty`).

PiperOrigin-RevId: 531273451